# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('sales', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'floor_2tu',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=10)),
                ('bgcolor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bg_lunbotu',
            },
        ),
    ]
