# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassesweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='bgcolor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
