# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glassesweb', '0002_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='floor2',
            table='glasses_floor2tu',
        ),
        migrations.AlterModelTable(
            name='user',
            table='glasses_user',
        ),
        migrations.AlterModelTable(
            name='wheel',
            table='glasses_lunbotu',
        ),
    ]
