# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glassesweb', '0004_auto_20190115_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glassesweb.Floor2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glassesweb.User')),
            ],
            options={
                'db_table': 'glasses_cart',
            },
        ),
        migrations.CreateModel(
            name='F2zhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'glasses_floor2zhi',
            },
        ),
    ]
