# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glassesweb', '0005_cart_f2zhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='f2zhi',
            name='img1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f2zhi',
            name='img2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f2zhi',
            name='img3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f2zhi',
            name='img4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
