# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_foottypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foottypes',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
    ]
